
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwmysql-deployment
  namespace: hwmysql-ns-hw-aws
  labels:
    app: hwmysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hwmysql
  template:
    metadata:
      labels:
        app: hwmysql
    spec:
      containers:
      - name: hwmysql
        image: bom.ocir.io/apaccpt01/php-heatwave-app:1.0.9
        ports:
        - containerPort: 80
        env:
        - name: HOST
          value: d8fcea22-b8df-4577-a12f-11702ff7009b.dbsystem.us-east-1.aws.cloud.mysql.com
        - name: DATABASE
          value: "ecommerce"
        - name: USERNAME
          value: "admin"
        - name: PASSWORD
          value: "Oracle#123"

---

apiVersion: v1
kind: Service
metadata:
  name: hwmysql-service
  namespace: hwmysql-ns-hw-aws
spec:
  type: LoadBalancer
  selector:
    app: hwmysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80