apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwmysql-deployment
  namespace: hwmysql-ns
  labels:
    app: hwmysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hwmysql
  template:
    metadata:
      labels:
        app: hwmysql
    spec:
      containers:
      - name: hwmysql
        image: hwmysql:1.14.2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: hwmysql-service
  namespace: hwmysql-ns
spec:
  type: LoadBalancer
  selector:
    app: hwmysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80